config/routes.rb
Rails.application.routes.draw do
  resources :accounts do  
  	resources :transactions
    resources :categories
    resources :import, only: [:new] do 
      collection {post :create }
    end
  end
  resources :transactions, only: [:index, :show, :edit] do 
    collection do 
      get :search
    end
  end
  resources :categories
  resources :analytics, only: [:index]
  
  root 'accounts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :transactions
  
  belongs_to :parent, class_name: "Category"
  has_many :children, class_name: "Category", foreign_key: "parent_id"

  validates :name, presence: true
  default_scope { order('name ASC') }

  def parent_name
    name = ("(" + Category.find(self.parent_id).name + ")") unless parent_id.nil?
  end

  def total_with_sub_categories
    self.transactions.sum(:amount) + self.children.includes(:transactions).sum(:amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
    # @categories = Category.joins(:transactions).merge(Transaction.unscoped.where("transactions.date > ?", Time.now - 1.year)).group("name")
    # @categories = Transaction.unscoped.last_year.joins(:category).select("categories.name").group(:category)
  end

  # GET /categories/1
  def show
    @transactions = @category.transactions
    @transaction_months = @transactions.group_by { |t| t.date.beginning_of_month }
    # @months = @transactions.select("date_trunc('month', date) as month, sum(amount) as total_amount").group('month')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :parent_id, collection: Category.all %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/_sub_categories.html.erb
<p>Sub-categories: </p>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th class="currency">Amount</th>
    </tr>
  <% @category.children.each do |cat| %>
  <tr>
    <td><%= link_to cat.name, category_path(cat) %></dt>
    <td class="currency"><%= number_to_currency(cat.transactions.sum(:amount)) %></dd>
  </td>
<% end %>
<tfoot>
  <tr>
    <td>Total</td>
    <td class="currency"><%= number_to_currency(@category.children.includes(:transactions).sum(:amount)) %></td>
</table>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table table-striped sortable categories">
  <thead>
    <tr class="table-row-heading">
      <th>Name</th>
      <th class="currency">Total Spending</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td data-value="<%= category.transactions.sum(:amount) %>" class="currency"><%= number_to_currency(category.transactions.sum(:amount)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %> <small><%= link_to @category.parent_name, category_path(@category.parent_id) unless !@category.parent_id %></small></h1>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<h2>
  <strong>Total:</strong>
  <%= number_to_currency(@category.total_with_sub_categories) %>
</h2>
<% if @category.children.exists? %>
  <%= render 'sub_categories' %>
<% end %>

<table class="table">
  <tr>
    <th>Month</th>
    <th class="currency">Amount</th>
  </tr>
  <% @transaction_months.each do |month, transactions| %>
  <tr>
    <td><%= month.strftime("%B %Y") %></td>
    <td class="currency"><%= number_to_currency(transactions.inject(0) {|sum, hash| sum + hash[:amount]}) %></td>
  </tr>
  <% end %>
</table>

<table class="table table-striped sortable">
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th class="currency">Amount</th>
    <th>Account</th>
  </tr>
  <% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.date %></td>
    <td><%= link_to transaction.description, account_transaction_path(transaction.account, transaction) %></td>
    <td class="currency"><%= number_to_currency(transaction.amount) %></td>
    <td><%= transaction.account.name %></td>
  </tr>
  <% end %>
</table>