config/routes.rb
Rails.application.routes.draw do
  resources :accounts do  
  	resources :transactions
    resources :categories
    resources :import, only: [:new] do 
      collection {post :create }
    end
  end
  resources :transactions, only: [:index, :show, :edit] do 
    collection do 
      get :search
    end
  end
  resources :categories
  resources :analytics, only: [:index]
  
  root 'accounts#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_account, only: [:show, :edit]

  after_action :update_account_balance, only: [:create, :update, :destroy]

  def index
    @transactions = Transaction.where(nil)
    filtering_params(params).each do |key, value|
      @transactions = @transactions.public_send(key, value) if value.present?
    end
    @transactions = @transactions.joins(:account).joins(:category).paginate(page: params[:page])
  end

  def search
    @transactions = Transaction.search(params[:search]).order('created_at DESC').joins(:account).paginate(page: params[:page])
  end

  def show
    @account = @transaction.account
  end

  def new
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.new
  end

  def edit
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      # @account.balance = @transaction.balance
      redirect_to account_path(@transaction.account), notice: 'Transaction saved!'
    else
      render :new
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to account_path(@transaction.account), notice: 'Transaction updated!'
    else
      render :edit
    end
  end

  def destroy
    @transaction.destroy
    redirect_to account_path(@transaction.account_id), notice: 'Transaction was successfully deleted.'
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_account
    @account = Account.find(params[:account_id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :description, 
      :amount, 
      :date, 
      :category_id, 
      :account_id, 
      :notes
    )
  end

  def update_account_balance
    @account = @transaction.account
    @account.balance = @account.account_total
  end

  def filtering_params(params)
    params.slice(:age)
  end
end

app/views/transactions/_form.html.erb
<%= simple_form_for [@transaction.account, @transaction] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :amount, as: :decimal %>
    <%= f.input :date, as: :string, input_html: {class: :datepicker}  %>
    <%= f.association :category, prompt: "Choose a Company" %>
    <%= f.association :account %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/_transactions.html.erb
  <section>
    <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% if @transactions.blank? %>
        <tr>
          <td colspan="7">There are no transactions to show.</td>
      <% else %>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.date %></td>
            <td><%= transaction.description %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.category.name %></td>
            <td><%= link_to 'Show', transaction %></td>
            <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
            <td><%= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  </section>
</section>

<section id="debug">
</section>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>
<%= link_to 'Delete', account_transaction_path(@transaction.account, @transaction), method: :delete, data: { confirm: "Are you sure you want to delete this transaction?" }, class: "btn btn-danger" %>

app/views/transactions/index.html.erb
<section>
  <h1>All Transactions</h1>
  <h2>Balance: </h2>
  <p>Filters</p>

  <p><%= link_to "Last 30 days", transactions_path(age: 30.to_i) %>
  <%= link_to "Last Quarter", transactions_path(age: 91.to_i) %>  
  <%= link_to "Last 6 months", transactions_path(age: (6.months.to_i)/1.days) %></p>
  <section>
    <%= will_paginate @transactions %>
    <table class="table table-striped sortable transactions">
      <thead>
        <tr>
          <th data-defaultsort="desc" data-dateformat="DD MMM YYYY">Date</th>
          <th>Description</th>
          <th class="currency" width="40">Amount</th>
          <th>Category</th>
          <th>Account</th>
          <th data-defaultsort="disabled"></th>
        </tr>
      </thead>

      <tbody>
      <% if @transactions.blank? %>
        <tr>
          <td colspan="7">There are no transactions to show.</td>
      <% else %>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.date %></td>
            <td class="description"><%= link_to transaction.description, transaction %></td>
            <td class="currency"><%= number_to_currency(transaction.amount, unit: "£") %></td>
            <td><%= transaction.category.name unless !transaction.category_id.present? %></td>
            <td><%= transaction.account.name %></td>
            <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
          </tr>
        <% end %>
      </tr>
      <% end %>
    </tbody>
    </table>
  </section>
</section>
<%= will_paginate @transactions %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/transactions/search.html.erb
<section>
  <h1>Searching "<%= params[:search] %>"</h1>
<p>Filters</p>

<%= link_to "Last 30 days", search_transactions_path(age: 30.to_i) %>
<%= link_to "Last Quarter", search_transactions_path(age: 91.to_i) %>  
<%= link_to "Last 6 months", search_transactions_path(age: (6.months/1.day)) %>  
<table class="table table-striped sortable">
  <thead>
    <tr>
      <th data-defaultsort="desc" data-dateformat="DD MMM YYYY">Date</th>
      <th>Description</th>
      <th width="40">Amount</th>
      <th>Category</th>
      <th>Account</th>
      <th data-defaultsort="disabled"></th>
    </tr>
  </thead>
  <tbody>
    <% if @transactions.blank? %>
      <tr>
        <td colspan="7">There are no transactions to show.</td>
    <% else %>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.date %></td>
          <td class="description">
            <%= link_to transaction.description, transaction %>
          </td>
          <td class="number"><%= number_to_currency(transaction.amount, unit: "£") %></td>
          <td><%= link_to transaction.category.name, category_path(transaction.category) unless !transaction.category_id.present? %></td>
          <td><%= transaction.account.name %></td>
          <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        </tr>
      <% end %>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">Total</td>
      <td class="number"><%= number_to_currency(@transactions.sum(:amount)) %></td>
      <td colspan="3"></>
  </tfoot>
</table>
</section>
<%= will_paginate @transactions %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>
<p>
  <strong>Notes:</strong>
  <%= @transaction.notes %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@transaction.amount) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category.name if @transaction.category %>
</p>
<p>
  <strong>Account</strong>
  <%= @transaction.account.name %>
</p>

<%= link_to 'Edit', edit_account_transaction_path(@account, @transaction) %> |
<%= link_to 'Back to Account', account_path(@account) %>