config/routes.rb
Rails.application.routes.draw do
  resources :accounts do  
  	resources :transactions
    resources :categories
    resources :import, only: [:new] do 
      collection {post :create }
    end
  end
  resources :transactions, only: [:index, :show, :edit] do 
    collection do 
      get :search
    end
  end
  resources :categories
  resources :analytics, only: [:index]
  
  root 'accounts#index'
end

app/views/layouts/_footer.html.erb
<%= render "javascript" %>
&copy; 2015 Nest Egg

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">NestEgg</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Accounts', accounts_path %></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <%= form_tag(search_transactions_path, method: 'get', class: 'navbar-form navbar-right') do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search...", class: 'form-control' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_nav.html.erb
<ul class="nav nav-sidebar">
  <li class="active"><a href="/">Overview <span class="sr-only">(current)</span></a></li>
  <li>Users</li>
  <li><%= link_to 'Accounts', accounts_path %></li>
  <li><%= link_to 'Categories', categories_path %></li>
  <ul>
    <li><%= link_to 'Transactions', transactions_path %></li>
  </ul>
  
</ul>
<ul class="nav nav-sidebar">
  <li><%= link_to t('titles.analytics'), analytics_path %></li>
</ul>
<ul class="nav nav-sidebar">
  <li><a href="#">Export</a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= ENV['LANG'] %>">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/nav' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= render "flashes" %>
        <%= yield %>
      </div>
    </div>
  </div>
  <footer>
  <%= render 'layouts/footer' %>
  <footer>
</body>
</html>