config/routes.rb
Rails.application.routes.draw do
  resources :accounts do  
  	resources :transactions
    resources :categories
    resources :import, only: [:new] do 
      collection {post :create }
    end
  end
  resources :transactions, only: [:index, :show, :edit] do 
    collection do 
      get :search
    end
  end
  resources :categories
  resources :analytics, only: [:index]
  
  root 'accounts#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :transactions, dependent: :destroy

  accepts_nested_attributes_for :transactions

  ACCOUNT_TYPE = ['Current Account', 'Credit Card', 'Savings']

  validates_presence_of :name, :balance, :opening_balance
  validates :name, uniqueness: true
  default_scope -> { order('name ASC') }
  scope :active, -> { where(status: 'active') }

  def account_total
    opening_balance + transactions.sum(:amount)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :update_balance, only: :show
  def index
    @accounts = Account.all
    @net_worth = Account.sum(:balance)
    @transactions = Transaction.limit(10)
  end

  def show
    @transactions = @account.transactions.includes(:category).paginate(page: params[:page])
  end

  def new
    @account = Account.new
  end

  def edit
    @account_name = @account.name
  end

  def create
    @account = Account.new(account_params)
    @account.balance = @account.opening_balance # replace this with a balance calculation after save
    if @account.save
      AccountMailer.new_account(@account).deliver_now
      redirect_to account_transactions_path(@account), notice: 'Your new account was created. You can now add or import your transactions.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    DeleteAccountJob.perform_now @account
    redirect_to accounts_url, notice: 'Account was deleted.'
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :account_type, :opening_balance, :balance, :overdraft, :organisation, :credit_interest, :debit_interest)
  end
  
  def update_balance
    @account.balance = @account.account_total
    @account.save
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :organisation %>
    <%= f.input :opening_balance %>
    <%= f.input :account_type, collection: Account::ACCOUNT_TYPE %>
    <%= f.input :overdraft %>
    <%= f.input :credit_interest %>
    <%= f.input :debit_interest %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/_import.html.erb
<section>
  <h2>Import from CSV</h2>
  <p>Import transactions from your bank's download facilities.</p>
  <%= form_tag import_account_transactions_path, multipart: true do %> 
    <%= check_box_tag headers %><%= label_tag "This file has header rows" %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</section>

app/views/accounts/_transactions.html.erb
<table class="table sortable transactions">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th class="currency">Amount</th>
      <th>Category</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% if @transactions.empty? %>
      <tr>
        <td colspan="7">There are no transactions to show.</td>
    <% else %>
      <% @transactions.each do |transaction| %>
        <tr>
          <td data-dateformat="DD MMM YYYY"><%= transaction.date %></td>
          <td>
            <%= link_to transaction.description, account_transaction_path(transaction.account, transaction) %>
            <small><%= "(" + transaction.account.name  + ")" unless @account %></small>
          </td>
          <td class="currency"><%= number_to_currency(transaction.amount) %></td>
          <td><%= link_to transaction.category, account_category_path(transaction.account, transaction) %></td>
          <td><%= link_to 'Edit', edit_account_transaction_path(transaction.account, transaction) %></td>
        </tr>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Back', @account, class: 'btn btn-info' %> |
<%= link_to 'Delete', @account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>
<p><%= link_to 'Add Account', new_account_path %>

<table class="table">
  <thead>
    <tr class="table-row-heading">
      <th>Name</th>
      <th class="right-text">Credit Limit</th>
      <th class="right-text">Balance</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr class="table-row" data-link="<%= account_path(account) %>">
        <td class="table-cell"><%= link_to account.name, account_path(account) %> - <small><%= account.organisation %></small></td>
        <td class="table-cell currency"><small><%= number_to_currency(account.overdraft) %></small></td>
        <td class="table-cell currency"><%= number_to_currency(account.account_total) %></td>
      </tr>
    <% end %>
    <tfoot>
      <tr>
        <td>Net Worth</td>
        <td class="number"><small><%= number_to_currency(@accounts.sum(:overdraft)) %></small></td>
        <td class="number"><%= number_to_currency(@net_worth) %></td>
      </tr>
    </tfoot>
  </tbody>
</table>
<h3>Latest transactions</h3>
<%= render 'transactions' %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<section>
  <%= link_to 'Back to accounts', accounts_path %>
  <h1><%= @account.name.titleize %> Transactions <small><%= @account.organisation %></small><%= link_to 'Edit', edit_account_path(@account), class: "btn" %></h1>
  <p>
  <h2>Balance <%= number_to_currency(@account.balance) %></h2>
  <h2>Total <%= number_to_currency(@account.account_total) %></h2>
  <%= link_to 'New Transaction', new_account_transaction_path(@account), class: 'btn btn-info' %>
  <%= link_to 'Import from CSV', new_account_import_path(@account), class: 'btn btn-info' %>

<p>
  <strong>Overdraft:</strong>
  <%= @account.overdraft %>
</p>

<p>
  <strong>Credit interest:</strong>
  <%= @account.credit_interest %>
</p>

<p>
  <strong>Debit interest:</strong>
  <%= @account.debit_interest %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %> | 

<%= render 'transactions' %>
<%= will_paginate @transactions %>